github:
  - org: MineInAbyss
    repos:
      StaminaClimb:
        tag: v0.2.1-alpha
      MineInAbyss:
        tag: v0.1.0-alpha
      DeeperWorld:
        tag: v0.1.3-alpha
      geary:
        artifacts: ["geary-.*-all.jar"]
      Mobzy:
        tag: v0.5.0-alpha
      AbyssalCreatures:
        tag: v0.1.1-alpha
  - org: CultOfClang
    repos:
      BoneHurtingJuice:
        tag: v1.0
